### ISSUE TITLE
brush lag

### ISSUE THREAD

**Issue by eagleyesss** [opentoonz/opentoonz_nightlies#8]
iam facing brush lag on the latest version of opentoonz since the  (Fix Lazy Nezumi Pro hooking Bug)

**Comment by RodneyBaker** [comment]
@eagleyesss Recommend closing this report and opening one on the Opentoonz repository.
This repo is only for the nightly builds which doesn't drive any changes to the software.

Link:  https://github.com/opentoonz/opentoonz/issues/new/choose
